spring:
  datasource:
    url: jdbc:mysql://localhost:3306/imagedb
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always #Spring2.5??????????????????????????????
      encoding: utf-8
  jpa:
    show-sql: true #hibernate??????sql???
    database: MYSQL
    hibernate:
      ddl-auto: none #Entity??????????????????
  # hibernate?Spring?Entity?????table?????(DDL)?data.sql???insert?????.
  # .sql??????????????????ddl-auto=none???
  # create??insert?? create-drop??????? update?????????
  thymeleaf:
    prefix: file:src/main/resources/templates/

bucket: test_strage00

#debug: true

#logging.level.org.springframework.security=trace